@urlBase=http://localhost:4000

### Pegar todos os generos
GET {{urlBase}}/info/generos

### Pegar todos os atores
GET {{urlBase}}/info/atores

### Pegar todos os diretores
GET {{urlBase}}/info/diretores